// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplikacjaWieloAgenty.Migrations
{
    [DbContext(typeof(GameConext))]
    [Migration("20220621165644_firstMigration.")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("AplikacjaWieloAgenty.Model.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AI")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BardzoTrudny")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Brak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kierownica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Klawiatura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Niski")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Online")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenWheel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rally")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sportowe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sredni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trudny")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
